---
# Java
- include: java.yml

# repo
- include: repo.yml

# Install Jenkins
- name: Install Jenkins
  yum:
    name: jenkins
    state: present
  notify:
    - Start Jenkins

# Install plugins
- include: plugins.yml

# Install CLI
- include: cli.yml
