---
port: 8080
repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
repo_dest: /etc/yum.repos.d/jenkins.repo
jenkins_rpm_key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
jenkins:
  base_url: 'http://ci-jenkins.com:8080'
  dest: '/opt/jenkins'
  cli_dest: '${jenkins.dest}/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '${jenkins.dest}/updates_jenkins.json' # Jenkins updates file
  plugins:
    - 'git'
    - 'github'
    - 'github-api'
    - 'ghprb'
